module.exports = {
    printWidth: 300,
    tabWidth: 4,
    useTabs: false,
    semi: false, // ステートメントの最後にセミコロン付与しない
    singleQuote: true,
    quoteProps: "as-needed",
    jsxSingleQuote: false,
    trailingComma: "es5",
    bracketSpacing: true,
    jsxBracketSameLine: false,
    arrowParens: "always",
    rangeStart: 0,
    rangeEnd: Infinity,
    parser: undefined,
    filePath: undefined,
    requirePragma: false,
    insertPragma: false,
    proseWrap: "preserve",
    htmlWhitespaceSensitivity: "css",
    vueIndentScriptAndStyle: false,
    endOfLine: "lf",
    embeddedLanguageFormatting: "auto",
}
